#!/bin/bash

__arch=$(uname -m)

if [ "${__arch}" = "aarch64" ]; then
    arch="arm64"
elif [ "${__arch}" = "x86_64" ]; then
    arch="amd64"
else
    echo "Architecture ${__arch} not recognized. Aborting."
    exit 1
fi

lastver=$(curl --silent "https://api.github.com/repos/ethereum/go-ethereum/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')

read -p "Update Geth to Version [$lastver]: " ver
ver=${ver:-$lastver}

sha=$(curl --silent "https://api.github.com/repos/ethereum/go-ethereum/git/ref/tags/${ver}" | grep -Po '"sha": "\K.*?(?=")')

echo
read -p "Are you sure you want to update Geth to Version [$ver - ${sha:0:8}]? (y/n)" -n 1 -r

echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

echo
echo "Downloading Geth Version: $ver"
curl -LO "https://gethstore.blob.core.windows.net/builds/geth-linux-$arch-${ver:1}-${sha:0:8}.tar.gz"

echo
echo "Importing build server public keys..."
gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys F9585DE6 C2FF8BBF 9BA28146 7B9E2481 D2A67EAC

echo
echo "Checking File Signature..."
curl -LO "https://gethstore.blob.core.windows.net/builds/geth-linux-$arch-${ver:1}-${sha:0:8}.tar.gz.asc" --silent

if ! gpg --verify geth-linux-$arch-${ver:1}-${sha:0:8}.tar.gz.asc; then
    echo
    echo "Signature Error!"
    exit 1
fi
echo 
echo "Signature OK!"

echo
echo "Stopping Geth Service..."
sudo systemctl stop geth

echo
echo "Extracting..."
tar xvf geth-linux-$arch-${ver:1}-${sha:0:8}.tar.gz
sudo cp ./geth-linux-$arch-${ver:1}-${sha:0:8}/geth /usr/local/bin

echo
read -p "Restart Geth Service?" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo
    echo "Starting Services..."
    echo "--------------------"
    sudo systemctl daemon-reload
    sudo systemctl start geth
fi

echo
echo "Cleaning Up..."
echo "--------------"
rm -r geth-linux-$arch-${ver:1}-${sha:0:8}
rm geth-linux-$arch-${ver:1}-${sha:0:8}.tar.gz
rm geth-linux-$arch-${ver:1}-${sha:0:8}.tar.gz.asc
