#!/bin/bash
lastver=$(curl --silent "https://api.github.com/repos/ethereum/go-ethereum/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')

read  -p "Update Geth to Version [$lastver]: " ver
ver=${ver:-$lastver}

lastsha=$(curl --silent "https://api.github.com/repos/ethereum/go-ethereum/git/ref/tags/${ver}" | grep -Po '"sha": "\K.*?(?=")')

read -p "Are you sure you want to update Geth to Version [$ver - ${lastsha:0:8}]? (y/n)" -n 1 -r

echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

echo
echo "Stopping Prysm Services..."
sudo systemctl stop mevboost
sudo systemctl stop prysmvalidator
sudo systemctl stop prysmbeacon

echo
echo "Stopping Geth Service..."
sudo systemctl stop geth

echo
echo "Sleeping for 10 seconds..."
sleep 10

echo
echo "Downloading Geth Version: $ver";
curl -LO "https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-${ver:1}-${lastsha:0:8}.tar.gz"

echo
echo "Extracting...";
tar xvf geth-linux-amd64-${ver:1}-${lastsha:0:8}.tar.gz
sudo cp ./geth-linux-amd64-${ver:1}-${lastsha:0:8}/geth /usr/local/bin

echo
read -p "Restart Services?" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
echo
echo "Starting Services..."
sudo systemctl daemon-reload
sudo systemctl start geth
sudo systemctl start prysmbeacon
sudo systemctl start prysmvalidator
sudo systemctl start mevboost
fi

echo
echo "Cleaning Up..."
rm -r geth-linux-amd64-${ver:1}-${lastsha:0:8}
rm geth-linux-amd64-${ver:1}-${lastsha:0:8}.tar.gz
