#!/bin/bash

__arch=$(uname -m)

if [ "${__arch}" = "aarch64" ]; then
    arch="arm64"
elif [ "${__arch}" = "x86_64" ]; then
    arch="amd64"
else
    echo "Architecture ${__arch} not recognized. Aborting."
    exit 1
fi

lastver=$(curl --silent "https://api.github.com/repos/prysmaticlabs/prysm/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')

read -p "Update Prysm to Version [$lastver]: " ver
ver=${ver:-$lastver}

read -p "Are you sure you want to update Prysm to Version [$ver]? (y/n)" -n 1 -r

echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

if [ "$(lscpu | grep -o adx)" ]; then
    echo
    echo "ADX Instruction set supported. Downloading modern linux binary."
    lx="modern-linux"
else
    echo
    echo "ADX Instruction set not supported. Downloading classic linux binary."
    lx="linux"
fi

echo
echo "Downloading Prysm: $ver"
echo "-----------------------------"
curl -LO https://github.com/prysmaticlabs/prysm/releases/download/$ver/beacon-chain-$ver-$lx-$arch
echo
curl -LO https://github.com/prysmaticlabs/prysm/releases/download/$ver/beacon-chain-$ver-$lx-$arch.sha256
echo
curl -LO https://github.com/prysmaticlabs/prysm/releases/download/$ver/validator-$ver-linux-$arch
echo
curl -LO https://github.com/prysmaticlabs/prysm/releases/download/$ver/validator-$ver-linux-$arch.sha256

echo
echo "Checking File integrity..."
echo "--------------------------"

if ! sha256sum --check "beacon-chain-$ver-$lx-$arch.sha256"; then
    echo
    echo "File Mismatch!"
    exit 1
fi

if ! sha256sum --check "validator-$ver-linux-$arch.sha256"; then
    echo
    echo "File Mismatch!"
    exit 1
fi

echo
echo "Stopping Prysm services..."
echo "--------------------------"
sudo systemctl stop prysmvalidator
sudo systemctl stop prysmbeacon

sleep 5

echo
echo "Moving binaries to /usr/local/bin"
echo "---------------------------------"
mv beacon-chain-$ver-$lx-$arch beacon-chain
mv validator-$ver-linux-$arch validator
sudo chmod +x beacon-chain
sudo chmod +x validator
sudo cp beacon-chain /usr/local/bin
sudo cp validator /usr/local/bin

read -p "Restart Prysm Services?" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo
    echo "Starting Prysm services..."
    echo "--------------------------"
    sudo systemctl daemon-reload
    sudo systemctl start prysmbeacon
    sudo systemctl start prysmvalidator
fi

echo "Cleaning up..."
echo "--------------"
rm beacon-chain
rm validator
rm beacon-chain-$ver-$lx-$arch.sha256
rm validator-$ver-linux-$arch.sha256
