#!/bin/bash

arch="amd64"
lastver=$(curl --silent "https://api.github.com/repos/prysmaticlabs/prysm/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')

read -p "Update Prysm to Version [$lastver]: " ver
ver=${ver:-$lastver}

read -p "Are you sure you want to update Prysm to Version [$ver]? (y/n)" -n 1 -r

echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

echo
echo "Downloading Prysm: $ver"
echo "-------------------------"
curl -LO https://github.com/prysmaticlabs/prysm/releases/download/$ver/beacon-chain-$ver-linux-$arch
echo
curl -LO https://github.com/prysmaticlabs/prysm/releases/download/$ver/validator-$ver-linux-$arch

echo
echo "Checking File integrity..."
echo "--------------------------"
curl -LO https://github.com/prysmaticlabs/prysm/releases/download/$ver/beacon-chain-$ver-linux-$arch.sha256 --silent
curl -LO https://github.com/prysmaticlabs/prysm/releases/download/$ver/validator-$ver-linux-$arch.sha256 --silent

if ! sha256sum --check "beacon-chain-$ver-linux-$arch.sha256"; then
    echo
    echo "File Mismatch!"
    exit 1
fi

if ! sha256sum --check "validator-$ver-linux-$arch.sha256"; then
    echo
    echo "File Mismatch!"
    exit 1
fi

echo
echo "Stopping Prysm services..."
echo "--------------------------"
sudo systemctl stop prysmvalidator
sudo systemctl stop prysmbeacon

echo
echo "Moving binaries to /usr/local/bin"
echo "---------------------------------"
mv beacon-chain-$ver-linux-$arch beacon-chain
mv validator-$ver-linux-$arch validator
sudo chmod +x beacon-chain
sudo chmod +x validator
sudo cp beacon-chain /usr/local/bin
sudo cp validator /usr/local/bin

read -p "Restart Prysm Services?" -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo
    echo "Starting Prysm services..."
    echo "--------------------------"
    sudo systemctl daemon-reload
    sudo systemctl start prysmbeacon
    sudo systemctl start prysmvalidator
fi

echo "Cleaning up..."
echo "--------------"
rm beacon-chain
rm validator
rm beacon-chain-$ver-linux-$arch.sha256
rm validator-$ver-linux-$arch.sha256
